services:
  db:
    image: postgres:16
    container_name: metoffice_postgres
    restart: always
    environment:
      POSTGRES_DB: metoffice_db
      POSTGRES_USER: prithvi
      POSTGRES_PASSWORD: db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: metoffice_backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: metoffice_db
      DB_USER: prithvi
      DB_PASSWORD: db
      DB_HOST: db
      DB_PORT: 5432

volumes:
  postgres_data:
